# Generated by Django 5.1.1 on 2024-09-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_description_and_more'),
        ('restaurants', '0002_restaurant_cuisine_type_restaurant_rating_favorite'),
    ]

    operations = [
    ]
