# Generated by Django 5.1.1 on 2024-09-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_merge_20240925_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
