# Generated by Django 5.1.1 on 2024-10-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_place_id'),
        ('restaurants', '0004_review'),
    ]

    operations = [
    ]
