# Generated by Django 5.1.2 on 2024-10-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
