# Generated by Django 5.1.2 on 2024-10-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_favoriterestaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteRestaurant',
        ),
    ]
